---
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 0161422b4e09b47536ea13f49e786eb3616fe0d7 # v2.4.0
    hooks:
      - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-json
      - id: check-toml

#  - repo: git://github.com/detailyang/pre-commit-shell
#    rev: 062f0b028ae65827e04f91c1e6738cfcbe9b337f # v1.0.6
#    hooks:
#      - id: shell-lint

  - repo: https://github.com/jorisroovers/gitlint
    rev: 2ba6564b82c125266091e2571563f7b957aec19c # 0.12.0
    hooks:
      - id: gitlint
        stages:
          - commit-msg
